name: roshab_tasks_mobile
description: Roshab Tasks student productivity app for Android and iOS.
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^22.2.0
  timezone: ^0.10.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
